### ISSUE TITLE
/sayas risk factor

### ISSUE THREAD

**Issue by qualitymanifest** [dangelspencer/shtbot#26]
Every once in a while, maybe if the millisecond timestamp of the request ends in a 0, don't perform the sayas correctly. Instead out the requester with a message from shtbot like `@${requester} tried to use /sayas @${victim} ${whatever they typed}, but idc`

The idea here isn't to discourage `/sayas` usage, I just think it would be hilarious to see it backfire sometimes

**Comment by dangelspencer** [comment]
made it a 1/100 chance to backfire, we can adjust as needed
